apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    name: redis-deployment
    app: guestbook-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guestbook-app
  template:
    metadata:
      name: redis-pod
      labels:
        app: guestbook-app

    spec:
      containers:
      - name: redis
        image: redis
        ports:
        - containerPort: 6379